enqueue:
    default:
        transport:
            dsn: 'mysql:'
            connection_factory_class: App\Queue\DbalConnectionFactory
            connection:
                driver: pdo_mysql
                host: '%env(resolve:ENQUEUE_DB_HOST)%'
                port: '%env(int:ENQUEUE_DB_PORT)%'
                dbname: '%env(resolve:ENQUEUE_DB_NAME)%'
                user: '%env(resolve:ENQUEUE_DB_USER)%'
                password: '%env(resolve:ENQUEUE_DB_PASSWORD)%'
                charset: utf8mb4
                serverVersion: '%env(resolve:ENQUEUE_DB_SERVER_VERSION)%'
        client: null
        extensions:
            doctrine_clear_identity_map_extension: true
            doctrine_closed_entity_manager_extension: true
            signal_extension:     true
